# Generated by Django 4.1.1 on 2022-09-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("date", models.DateField(auto_created=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("activity", models.CharField(max_length=100)),
                ("minutes", models.IntegerField()),
                ("notes", models.CharField(max_length=100)),
            ],
        ),
    ]
