# Generated by Django 4.1.1 on 2022-09-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
