# Generated by Django 4.1.1 on 2022-09-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelog", "0002_alter_log_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log", name="date", field=models.DateField(auto_now_add=True),
        ),
    ]
